---
- name: Connectivity test for IPv4 hosts
  hosts: v4host-mgmt
  tasks:
    - name: Ping between IPv4 hosts
      command: ping -I eth1 -c 1 -W 1 {{ item }}
      changed_when: false
      ignore_errors: yes
      with_items: "{{ groups['v4host-fabric'] }}"
    - name: Ping from hosts to Google public DNS IPv4
      command: ping -I eth1 -c 1 -W 1 {{ item }}
      changed_when: false
      ignore_errors: yes
      with_items: "{{ groups['google-dns-v4'] }}"

- name: Connectivity test for IPv6 hosts
  hosts: v6host-mgmt
  tasks:
    - name: Ping between IPv6 hosts
      command: ping6 -I eth1 -c 1 -W 1 {{ item }}
      changed_when: false
      ignore_errors: yes
      with_items: "{{ groups['v6host-fabric'] }}"
    - name: Ping6 from hosts to Google public DNS IPv6
      command: ping -I eth1 -c 1 -W 1 {{ item }}
      changed_when: false
      ignore_errors: yes
      with_items: "{{ groups['google-dns-v6'] }}"

- name: Connectivity test for quagga
  hosts: quagga-mgmt
  tasks:
    - name: Ping from quagga to upstream
      command: ping -I eth1 -c 1 -W 1 {{ item }}
      changed_when: false
      ignore_errors: yes
      with_items: "{{ groups['upstream'] }}"
